# Generated by cpp11: do not edit by hand

create_circle_2_empty <- function() {
  .Call("_euclid_create_circle_2_empty")
}

create_circle_2_center_radius <- function(center, r) {
  .Call("_euclid_create_circle_2_center_radius", center, r)
}

create_circle_2_3_point <- function(p, q, r) {
  .Call("_euclid_create_circle_2_3_point", p, q, r)
}

create_circle_2_2_point <- function(p, q) {
  .Call("_euclid_create_circle_2_2_point", p, q)
}

create_exact_numeric <- function(numeric) {
  .Call("_euclid_create_exact_numeric", numeric)
}

exact_numeric_length <- function(ex_n) {
  .Call("_euclid_exact_numeric_length", ex_n)
}

exact_numeric_subset <- function(ex_n, index) {
  .Call("_euclid_exact_numeric_subset", ex_n, index)
}

exact_numeric_assign <- function(ex_n, index, value) {
  .Call("_euclid_exact_numeric_assign", ex_n, index, value)
}

exact_numeric_combine <- function(ex_n, extra) {
  .Call("_euclid_exact_numeric_combine", ex_n, extra)
}

exact_numeric_is_na <- function(ex_n) {
  .Call("_euclid_exact_numeric_is_na", ex_n)
}

exact_numeric_any_na <- function(ex_n) {
  .Call("_euclid_exact_numeric_any_na", ex_n)
}

exact_numeric_to_numeric <- function(ex_n) {
  .Call("_euclid_exact_numeric_to_numeric", ex_n)
}

exact_numeric_is_equal <- function(ex_n, ex_n2) {
  .Call("_euclid_exact_numeric_is_equal", ex_n, ex_n2)
}

exact_numeric_is_not_equal <- function(ex_n, ex_n2) {
  .Call("_euclid_exact_numeric_is_not_equal", ex_n, ex_n2)
}

exact_numeric_less <- function(ex_n, ex_n2) {
  .Call("_euclid_exact_numeric_less", ex_n, ex_n2)
}

exact_numeric_less_equal <- function(ex_n, ex_n2) {
  .Call("_euclid_exact_numeric_less_equal", ex_n, ex_n2)
}

exact_numeric_greater <- function(ex_n, ex_n2) {
  .Call("_euclid_exact_numeric_greater", ex_n, ex_n2)
}

exact_numeric_greater_equal <- function(ex_n, ex_n2) {
  .Call("_euclid_exact_numeric_greater_equal", ex_n, ex_n2)
}

exact_numeric_unique <- function(ex_n) {
  .Call("_euclid_exact_numeric_unique", ex_n)
}

exact_numeric_duplicated <- function(ex_n) {
  .Call("_euclid_exact_numeric_duplicated", ex_n)
}

exact_numeric_any_duplicated <- function(ex_n) {
  .Call("_euclid_exact_numeric_any_duplicated", ex_n)
}

exact_numeric_rank <- function(ex_n) {
  .Call("_euclid_exact_numeric_rank", ex_n)
}

exact_numeric_match <- function(ex_n, table) {
  .Call("_euclid_exact_numeric_match", ex_n, table)
}

exact_numeric_plus <- function(ex_n, ex_n2) {
  .Call("_euclid_exact_numeric_plus", ex_n, ex_n2)
}

exact_numeric_minus <- function(ex_n, ex_n2) {
  .Call("_euclid_exact_numeric_minus", ex_n, ex_n2)
}

exact_numeric_uni_minus <- function(ex_n) {
  .Call("_euclid_exact_numeric_uni_minus", ex_n)
}

exact_numeric_times <- function(ex_n, ex_n2) {
  .Call("_euclid_exact_numeric_times", ex_n, ex_n2)
}

exact_numeric_divided <- function(ex_n, ex_n2) {
  .Call("_euclid_exact_numeric_divided", ex_n, ex_n2)
}

exact_numeric_abs <- function(ex_n) {
  .Call("_euclid_exact_numeric_abs", ex_n)
}

exact_numeric_sign <- function(ex_n) {
  .Call("_euclid_exact_numeric_sign", ex_n)
}

exact_numeric_cumsum <- function(ex_n) {
  .Call("_euclid_exact_numeric_cumsum", ex_n)
}

exact_numeric_cumprod <- function(ex_n) {
  .Call("_euclid_exact_numeric_cumprod", ex_n)
}

exact_numeric_cummax <- function(ex_n) {
  .Call("_euclid_exact_numeric_cummax", ex_n)
}

exact_numeric_cummin <- function(ex_n) {
  .Call("_euclid_exact_numeric_cummin", ex_n)
}

exact_numeric_diff <- function(ex_n, lag) {
  .Call("_euclid_exact_numeric_diff", ex_n, lag)
}

exact_numeric_sort <- function(ex_n, decreasing, na_last) {
  .Call("_euclid_exact_numeric_sort", ex_n, decreasing, na_last)
}

exact_numeric_sum <- function(ex_n, na_rm) {
  .Call("_euclid_exact_numeric_sum", ex_n, na_rm)
}

exact_numeric_prod <- function(ex_n, na_rm) {
  .Call("_euclid_exact_numeric_prod", ex_n, na_rm)
}

exact_numeric_min <- function(ex_n, na_rm) {
  .Call("_euclid_exact_numeric_min", ex_n, na_rm)
}

exact_numeric_max <- function(ex_n, na_rm) {
  .Call("_euclid_exact_numeric_max", ex_n, na_rm)
}

geometry_length <- function(geometries) {
  .Call("_euclid_geometry_length", geometries)
}

geometry_dimension <- function(geometries) {
  .Call("_euclid_geometry_dimension", geometries)
}

geometry_cardinality <- function(geometries) {
  .Call("_euclid_geometry_cardinality", geometries)
}

geometry_subset <- function(geometries, index) {
  .Call("_euclid_geometry_subset", geometries, index)
}

geometry_copy <- function(geometries) {
  .Call("_euclid_geometry_copy", geometries)
}

geometry_assign <- function(geometries, index, value) {
  .Call("_euclid_geometry_assign", geometries, index, value)
}

geometry_combine <- function(geometries, extra) {
  .Call("_euclid_geometry_combine", geometries, extra)
}

geometry_unique <- function(geometries) {
  .Call("_euclid_geometry_unique", geometries)
}

geometry_duplicated <- function(geometries) {
  .Call("_euclid_geometry_duplicated", geometries)
}

geometry_any_duplicated <- function(geometries) {
  .Call("_euclid_geometry_any_duplicated", geometries)
}

geometry_match <- function(geometries, table) {
  .Call("_euclid_geometry_match", geometries, table)
}

geometry_is_na <- function(geometries) {
  .Call("_euclid_geometry_is_na", geometries)
}

geometry_any_na <- function(geometries) {
  .Call("_euclid_geometry_any_na", geometries)
}

geometry_to_matrix <- function(geometries) {
  .Call("_euclid_geometry_to_matrix", geometries)
}

geometry_format <- function(geometries) {
  .Call("_euclid_geometry_format", geometries)
}

geometry_is_equal <- function(geometries1, geometries2) {
  .Call("_euclid_geometry_is_equal", geometries1, geometries2)
}

geometry_is_not_equal <- function(geometries1, geometries2) {
  .Call("_euclid_geometry_is_not_equal", geometries1, geometries2)
}

geometry_is_degenerate <- function(geometries) {
  .Call("_euclid_geometry_is_degenerate", geometries)
}

create_point_2_empty <- function() {
  .Call("_euclid_create_point_2_empty")
}

create_point_2_x_y <- function(x, y) {
  .Call("_euclid_create_point_2_x_y", x, y)
}

create_point_2_vec <- function(p) {
  .Call("_euclid_create_point_2_vec", p)
}

point_2_add_vector <- function(x, y) {
  .Call("_euclid_point_2_add_vector", x, y)
}

point_2_sub_vector <- function(x, y) {
  .Call("_euclid_point_2_sub_vector", x, y)
}

point_2_sub_point <- function(x, y) {
  .Call("_euclid_point_2_sub_point", x, y)
}

point_2_less <- function(x, y) {
  .Call("_euclid_point_2_less", x, y)
}

point_2_less_equal <- function(x, y) {
  .Call("_euclid_point_2_less_equal", x, y)
}

point_2_greater <- function(x, y) {
  .Call("_euclid_point_2_greater", x, y)
}

point_2_greater_equal <- function(x, y) {
  .Call("_euclid_point_2_greater_equal", x, y)
}

point_2_coord <- function(x, i) {
  .Call("_euclid_point_2_coord", x, i)
}

point_2_sort <- function(x, decreasing, na_last) {
  .Call("_euclid_point_2_sort", x, decreasing, na_last)
}

point_2_rank <- function(x) {
  .Call("_euclid_point_2_rank", x)
}

point_2_min <- function(x, na_rm) {
  .Call("_euclid_point_2_min", x, na_rm)
}

point_2_max <- function(x, na_rm) {
  .Call("_euclid_point_2_max", x, na_rm)
}

create_point_3_empty <- function() {
  .Call("_euclid_create_point_3_empty")
}

create_point_3_x_y_z <- function(x, y, z) {
  .Call("_euclid_create_point_3_x_y_z", x, y, z)
}

create_point_3_vec <- function(p) {
  .Call("_euclid_create_point_3_vec", p)
}

point_3_add_vector <- function(x, y) {
  .Call("_euclid_point_3_add_vector", x, y)
}

point_3_sub_vector <- function(x, y) {
  .Call("_euclid_point_3_sub_vector", x, y)
}

point_3_sub_point <- function(x, y) {
  .Call("_euclid_point_3_sub_point", x, y)
}

point_3_less <- function(x, y) {
  .Call("_euclid_point_3_less", x, y)
}

point_3_less_equal <- function(x, y) {
  .Call("_euclid_point_3_less_equal", x, y)
}

point_3_greater <- function(x, y) {
  .Call("_euclid_point_3_greater", x, y)
}

point_3_greater_equal <- function(x, y) {
  .Call("_euclid_point_3_greater_equal", x, y)
}

point_3_coord <- function(x, i) {
  .Call("_euclid_point_3_coord", x, i)
}

point_3_sort <- function(x, decreasing, na_last) {
  .Call("_euclid_point_3_sort", x, decreasing, na_last)
}

point_3_rank <- function(x) {
  .Call("_euclid_point_3_rank", x)
}

point_3_min <- function(x, na_rm) {
  .Call("_euclid_point_3_min", x, na_rm)
}

point_3_max <- function(x, na_rm) {
  .Call("_euclid_point_3_max", x, na_rm)
}

create_vector_2_empty <- function() {
  .Call("_euclid_create_vector_2_empty")
}

create_vector_2_point <- function(p) {
  .Call("_euclid_create_vector_2_point", p)
}

create_vector_2_x_y <- function(x, y) {
  .Call("_euclid_create_vector_2_x_y", x, y)
}

vector_2_add_vector <- function(x, y) {
  .Call("_euclid_vector_2_add_vector", x, y)
}

vector_2_minus_vector <- function(x, y) {
  .Call("_euclid_vector_2_minus_vector", x, y)
}

vector_2_negate <- function(x) {
  .Call("_euclid_vector_2_negate", x)
}

vector_2_dot_vector <- function(x, y) {
  .Call("_euclid_vector_2_dot_vector", x, y)
}

vector_2_times_numeric <- function(x, y) {
  .Call("_euclid_vector_2_times_numeric", x, y)
}

vector_2_divide_numeric <- function(x, y) {
  .Call("_euclid_vector_2_divide_numeric", x, y)
}

vector_2_sum <- function(x, na_rm) {
  .Call("_euclid_vector_2_sum", x, na_rm)
}

vector_2_coord <- function(x, i) {
  .Call("_euclid_vector_2_coord", x, i)
}

create_vector_3_empty <- function() {
  .Call("_euclid_create_vector_3_empty")
}

create_vector_3_point <- function(p) {
  .Call("_euclid_create_vector_3_point", p)
}

create_vector_3_x_y_z <- function(x, y, z) {
  .Call("_euclid_create_vector_3_x_y_z", x, y, z)
}

vector_3_add_vector <- function(x, y) {
  .Call("_euclid_vector_3_add_vector", x, y)
}

vector_3_minus_vector <- function(x, y) {
  .Call("_euclid_vector_3_minus_vector", x, y)
}

vector_3_negate <- function(x) {
  .Call("_euclid_vector_3_negate", x)
}

vector_3_dot_vector <- function(x, y) {
  .Call("_euclid_vector_3_dot_vector", x, y)
}

vector_3_times_numeric <- function(x, y) {
  .Call("_euclid_vector_3_times_numeric", x, y)
}

vector_3_divide_numeric <- function(x, y) {
  .Call("_euclid_vector_3_divide_numeric", x, y)
}

vector_3_sum <- function(x, na_rm) {
  .Call("_euclid_vector_3_sum", x, na_rm)
}

vector_3_coord <- function(x, i) {
  .Call("_euclid_vector_3_coord", x, i)
}
